import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "../../graphql/apolloProvider"; // <-- IMPORTA IL WRAPPER

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* AVVOLGI I CHILDREN CON IL WRAPPER */}
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}